In [1]:
import numpy as np

# **DataTypes & Attributes**

In [2]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2, 3],
              [6., 2., 3.]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6]],
               [[7, 8, 9],
                [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18]]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a3.shape

(3, 2, 3)

In [8]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# **1. Create a DataFrame from NumPy array**

In [12]:
import pandas as pd

In [13]:
df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.0
1  6.0  2.0  3.0

# **2. Creating Arrays**

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int64')

In [16]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros((2, 5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 4, 6, 8, 7],
       [5, 9, 8, 6, 7],
       [4, 2, 9, 6, 8]])

In [22]:
random_array.size

15

In [23]:
random_array_2 = np.random.random((7, 3))
random_array_2

array([[0.29962603, 0.20812708, 0.76312136],
       [0.9323746 , 0.1643746 , 0.11954398],
       [0.50624694, 0.15963748, 0.03154242],
       [0.87600889, 0.97195647, 0.31067823],
       [0.78527239, 0.80055906, 0.6058978 ],
       [0.23327967, 0.99184731, 0.67338964],
       [0.98957873, 0.67681881, 0.42902485]])

In [24]:
random_array_2.shape

(7, 3)

In [25]:
random_array_3 = np.random.rand(7, 3)
random_array_3

array([[0.27466525, 0.18668293, 0.43441117],
       [0.36799535, 0.13639629, 0.33081546],
       [0.49268887, 0.55796163, 0.76587767],
       [0.2316246 , 0.49432746, 0.66495137],
       [0.48705043, 0.57862432, 0.21437498],
       [0.46413909, 0.49992575, 0.20756953],
       [0.13440214, 0.71461931, 0.26468005]])

# **Pseduo-random numbers**

Allows us to generate random numbers **that are reproducable**

np.random.seed(0)

In [26]:
np.random.seed(0)
random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [27]:
random_array_4.shape

(5, 3)

In [28]:
np.random.seed(534534)
random_array_5 = np.random.random((7, 3))
random_array_5

array([[0.88328013, 0.51795149, 0.51175374],
       [0.87606269, 0.6723228 , 0.05636686],
       [0.97618157, 0.25876553, 0.05352877],
       [0.3595396 , 0.61136744, 0.52753095],
       [0.46623891, 0.04640886, 0.85615742],
       [0.76264365, 0.377411  , 0.8633925 ],
       [0.26916801, 0.60579248, 0.91275654]])

# **2. Viweing Arrays & Matrices**

In [29]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a1[0]

1

In [31]:
a2[0][1]

2.0

**First 2 values of every item**

In [32]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [33]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 3, 2, 6],
         [7, 7, 7, 7, 9],
         [3, 4, 8, 5, 8],
         [1, 2, 8, 5, 1]],

        [[3, 2, 8, 4, 0],
         [1, 8, 2, 9, 3],
         [1, 9, 8, 4, 3],
         [3, 4, 1, 6, 4]],

        [[7, 9, 8, 2, 9],
         [2, 4, 7, 0, 9],
         [0, 3, 1, 4, 8],
         [0, 9, 3, 0, 4]]],


       [[[0, 2, 5, 2, 7],
         [2, 1, 4, 6, 4],
         [5, 1, 5, 6, 1],
         [6, 0, 1, 9, 2]],

        [[8, 4, 8, 7, 6],
         [6, 6, 5, 1, 0],
         [8, 1, 5, 2, 5],
         [4, 9, 8, 7, 2]],

        [[9, 6, 7, 9, 6],
         [6, 2, 2, 2, 7],
         [8, 9, 4, 3, 6],
         [1, 9, 2, 3, 4]]]])

In [34]:
a4[:2, :2, :2, :2]

array([[[[3, 5],
         [7, 7]],

        [[3, 2],
         [1, 8]]],


       [[[0, 2],
         [2, 1]],

        [[8, 4],
         [6, 6]]]])

In [35]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [36]:
a4[:1, :1, :1, :4]

array([[[[3, 5, 3, 2]]]])

In [37]:
a4[:, :, :, :4]

array([[[[3, 5, 3, 2],
         [7, 7, 7, 7],
         [3, 4, 8, 5],
         [1, 2, 8, 5]],

        [[3, 2, 8, 4],
         [1, 8, 2, 9],
         [1, 9, 8, 4],
         [3, 4, 1, 6]],

        [[7, 9, 8, 2],
         [2, 4, 7, 0],
         [0, 3, 1, 4],
         [0, 9, 3, 0]]],


       [[[0, 2, 5, 2],
         [2, 1, 4, 6],
         [5, 1, 5, 6],
         [6, 0, 1, 9]],

        [[8, 4, 8, 7],
         [6, 6, 5, 1],
         [8, 1, 5, 2],
         [4, 9, 8, 7]],

        [[9, 6, 7, 9],
         [6, 2, 2, 2],
         [8, 9, 4, 3],
         [1, 9, 2, 3]]]])